# Generated by Django 4.1.2 on 2023-04-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publisher', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.TextField()),
                ('na_sales', models.FloatField()),
                ('eu_sales', models.FloatField()),
                ('jp_sales', models.FloatField()),
                ('other_sales', models.FloatField()),
                ('global_sales', models.FloatField()),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.publisher')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.year')),
            ],
        ),
    ]
