# Generated by Django 4.1.2 on 2023-04-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platform',
            new_name='platform_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher',
            new_name='publisher_name',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year_no',
        ),
    ]
