# Generated by Django 4.1.2 on 2023-04-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_id_alter_genre_id_alter_platform_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
