# Generated by Django 4.1.2 on 2023-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='staff',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
