# Generated by Django 4.1.2 on 2023-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_customer_admin_alter_order_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='staff',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'staff'), ('Customer', 'customer'), ('Admin', 'admin')], default='customer', max_length=8),
        ),
    ]
