# Generated by Django 4.1.2 on 2023-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_customer_admin_remove_customer_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'staff'), ('Customer', 'customer'), ('Admin', 'admin')], max_length=8),
        ),
    ]
